### ISSUE TITLE
Improvement of error handling

### ISSUE THREAD

**Issue by caunt** [CurseForgeCommunity/.NET-APIClient#4]
Hello! First of all, I'd like to say thank you for such a great implementation of CurseForge API. I have just a few improvements ideas I'd like to see. 

Recently, I started looking for Mod Files using ProjectId and FileId from Minecraft modpacks manifest.json file. Most of them was successfuly found, but some have missing files. I mean, mods being deleted from CurseForge. So ApiClient class have to throw not a very informative Exception about it, as CurseForge API response was 404 NotFound StatusCode. This messes up with many another http exceptions, where rate-limit gets applied or API key have been rejected. 

I'd like to ask you just add some information about "bad" response being received. Split all types of CurseForge API exception to different classes, or at least, add a Message property to Exception, so we can identify Mods that cannot be found, or Rate Limit exception.

**Comment by itssimple** [comment]
Of course. It wasn't something I thought a lot about when I built this project, as I didn't know anyone else would use it. ^^

**Comment by itssimple** [comment]
Sorry for the delay, a lot of IRL stuff happening! But will fix this week!

**Comment by itssimple** [comment]
## Fetching World of Warcraft (gameId 1)
![image](https://github.com/user-attachments/assets/cf11a7bf-990f-4f60-91eb-ba013fa69835)

## Fetching gameId -1
![image](https://github.com/user-attachments/assets/e1ef19dd-045a-4eb4-8336-1a203979e1ec)

**Comment by itssimple** [comment]
Version 3.0.0 uploaded to Nuget!
